services:
  mongo:
    image: mongo:6.0
    restart: always
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  backend:
    build: ./backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/cron-service
      - PORT=5000
    depends_on:
      - mongo

  backend-bonus:
    build: ./backend
    restart: always
    ports:
      - "5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/cron-service
      - PORT=5000
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongo-data:
